In [1]:
import pandas as pd

In [4]:
#Data Frame
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [19]:
# Columns
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"],index=["x","y","z"])
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [9]:
# Head Gives top element
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"])
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"])
df.head(1)

   A  B  C
0  1  2  3

In [11]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"])
df.head(2)

   A  B  C
0  1  2  3
1  4  5  6

In [12]:
# Tail Gives bottom element
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"])
df.tail(1)

   A  B  C
2  7  8  9

In [13]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [15]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [16]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [17]:
df.index.tolist()

[0, 1, 2]

In [20]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [23]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [25]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [26]:
df.shape

(3, 3)